# Este é um exemplo de arquivo de configuração. Para utilizá-lo, configure as variáveis 
# marcadas com o comentário # placeholder e renomeie o arquivo para config.yaml.

ibm: IBM
bovespa: BOVB11.SAO
alphavantage_api_keys:
  - API_KEY_1 # placeholder
  - API_KEY_2 # placeholder
  - API_KEY_3 # placeholder