version: '3.8'
services:
  # Postgres
  postgres:
    image: postgres:13.0-alpine
    container_name: bovespa-empresas-database
    restart: always
    environment:
      - POSTGRES_PASSWORD=PLACEHOLDER_PASSWORD
  # Redis
  redis:
    image: redis:3.2-alpine
    container_name: bovespa-empresas-redis
    restart: always
  # Backend Bovespa/Empresas
  app:
    container_name: bovespa-empresas-backend
    build: "."
    restart: always
    volumes:
      - ".:/backend"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis