version: '3.8'
services:
  # Postgres
  postgres:
    image: postgres:13.0-alpine
    container_name: bovespa-empresas-database
    restart: always
    environment:
      - POSTGRES_PASSWORD=PLACEHOLDER_PASSWORD
  # Redis
  redis:
    image: redis:3.2-alpine
    container_name: bovespa-empresas-redis
    restart: always
  # Tor
  tor:
    image: dperson/torproxy
    container_name: bovespa-empresas-tor
    ports:
      - 8118:8118
      - 9050:9050
    environment:
      - TOR_NewCircuitPeriod=10
  # Publisher de cotações
  publisher:
    build:
      context: "."
      dockerfile: ./publisher/Dockerfile
    container_name: bovespa-empresas-publisher
    restart: always
    volumes:
      - ".:/backend"
    ports:
      - 5556:5556
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
      - tor
  # Backend Bovespa/Empresas
  app:
    build: "."
    container_name: bovespa-empresas-backend
    restart: always
    volumes:
      - ".:/backend"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - tor